Layout/LineLength:
  Max: 80
  Exclude:
    - '*.gemspec'

Style/Documentation:
  Enabled: true

# Future Cops - 1.0
Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
